apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-devops-app
  description: ADO Janitor
  tags:
    - Go
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: system-janitor
